firstday: 92
lastday: 122
outfile: train.csv
files:
    smooth_afghan_AMSRE_h23v05_WY2009.h5:
        dayoffset: 92
        datasets:
            Grid/MODIS_GRID_10km/amsr_swe_smoothed: amsr_swe_smoothed
    h23v05_WY2009_10km.h5:
        dayoffset: 92
        datasets:
            Grid/MODIS_GRID_10km/sca_mean: sca_mean
            Grid/MODIS_GRID_10km/sca_stddev: sca_stddev
    ReconSWE_h23v05_2009_10km.h5:
        dayoffset: 0
        datasets:
            Grid/MODIS_GRID_10km/swe_mean: recon_swe_mean
